# This is a basic workflow to help you get started with Actions

name: Crawl data

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 7 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup git
        run: |
          git switch main
          git config --global user.name "Crawler"
          git config --global user.email "null@github.com"
          git remote set-url --push origin https://d3n972:${GITHUB_TOKEN}@github.com/OpenDataHU/treasury_bond_stats.git
      - name: Run a multi-line script
        run: |
          apt update&&apt install -y curl jq
          curl "https://www.allampapir.hu/api/network_rate/m/get_prices/DKJ" \
           |jq -r '.data.data|(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' \
           > $(date "+DKJ-%Y-%m-%d.csv")
      - name: Commit data
        run: git add *&& git commit -m "Update on $(date '+%Y-%m-%d')" && git push
